high: &high
  daily_disbursements:
    cron: "30 0 * * *"
    class: "DailyDisbursementJob"
    queue: high
    description: "Create daily disbursements"

  weekly_disbursements:
    cron: "30 0 * * *"
    class: "WeeklyDisbursementJob"
    queue: high
    description: "Create weelky disbursements"
